apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grocy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://geek-cookbook.github.io/charts/
    chart: geek-cookbook/grocy
    targetRevision: 8.5.2
  destination:
    server: https://kubernetes.default.svc
    namespace: grocy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
