apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komga
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://geek-cookbook.github.io/charts
    chart: komga
    targetRevision: 2.4.2
  destination:
    server: https://kubernetes.default.svc
    namespace: komga
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
