apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deluge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts/
    chart: deluge
    targetRevision: 5.4.2
  destination:
    server: https://kubernetes.default.svc
    namespace: deluge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
