apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kavita
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.truecharts.org/
    chart: kavita
    targetRevision: 1.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kavita
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
